# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-16 02:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aplicacion', '0003_auto_20180315_2107'),
    ]

    operations = [
        migrations.AddField(
            model_name='partido',
            name='finalizado',
            field=models.BooleanField(default=False),
        ),
    ]
