# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-13 22:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aplicacion', '0006_auto_20180403_2311'),
    ]

    operations = [
        migrations.AddField(
            model_name='grupo',
            name='partidos',
            field=models.ManyToManyField(to='Aplicacion.Partido'),
        ),
    ]
