# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-16 17:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aplicacion', '0007_grupo_partidos'),
    ]

    operations = [
        migrations.AddField(
            model_name='grupo',
            name='imagen',
            field=models.ImageField(default=None, upload_to=b''),
            preserve_default=False,
        ),
    ]
